### PR TITLE
fix(rust-sdk): handle metadata fields returned as arrays

### LINKED ISSUE #1304: [Bug] Rust SDK check_crawl_status errors if there are arrays in the metadata
**Describe the Bug**
I suspect that when calling check_crawl_status, the Rust SDK expects all of the metadata fields to be strings, even though sometimes they can be Vec<Strings>.

For example
```
"viewport": ["width=device-width, initial-scale=1", "width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no,viewport-fit=cover"]
```

or

```
"twitter:image": ["http://localhost:3000/#{FALLBACK_IMAGE}", "https://images.contentstack.io/v3/assets/bltdc2476c7b6b194dd/blt46acaa0d3fe3fd06/66db08a7b89507bdf18d1c3d/Sports_Impact_Report.jpg"]
```

If you have a crawl with vector metadata like this, then the Rust SDK will throw the error
```
Error: Failed to parse response: invalid type: sequence, expected a string
```

However, if your crawl has only string fields in the metadata, it works as expected.

**To Reproduce**
1. Get a crawl with vectors in the metadata
2. Call check_crawl_status with that crawl id using the rust sdk

**Expected Behavior**
The sdk should throw an error

**Environment (please complete the following information):**
- OS: macOS Sequoia 15.3
- Firecrawl Rust SDK Version: 1.0.0
- Node.js Version: N/A

### PR DESCRIPTION
**Pull request by madmikeross**
The API returns arrays for DocumentMetadata fields (e.g. `"robots": ["index", "follow"]`) when a page has duplicate meta tags, but the Rust SDK types these as `Option<String>`, causing serde to fail with `"invalid type: sequence, expected a string"`.

This adds a custom `deserialize_string_or_array` serde helper that accepts both `String` and `[String]`, joining arrays with `", "`. All `Option<String>` metadata fields in both v1 and v2 DocumentMetadata structs are annotated with it. The public type signature stays `Option<String>` so this is a non-breaking change.

New unit tests cover string values, array values, null, missing fields, empty arrays, single-element arrays, serialization roundtrip, and full document parsing.

Fixes #1304

### CODE REVIEW

**Comment by madmikeross** [comment]
@mogery or @abimaelmartell could you please approve workflows when you have a chance? Or offer guidance on preferred approach?

**Comment by madmikeross** [comment]
@mogery @abimaelmartell thanks for kicking off the workflows. Build and test passed. It looks like the other failures are pre-existing or unrelated (usual report publish failure due to fork perms).

**Comment by abimaelmartell** [comment]
hey @madmikeross could you reuse `deserialize_string_or_array`? Seems to be duplicated.

Thank you for your contribution!

File: apps/rust-sdk/src/document.rs [hunk 1]
```diff
@@ -1,6 +1,33 @@
...
+            if strings.is_empty() {
+                Ok(None)
+            } else {
+                Ok(Some(strings.join(", ")))
+            }
+        }
+        Some(other) => Ok(Some(other.to_string())),
+    }
+}
+
```
Comment (abimaelmartell) [inline apps/rust-sdk/src/document.rs]: Could you reuse this? Maybe extract into a shared module (eg serde_helpers.rs), and importing it in both places to keep things DRY.

Same for the test suites which are nearly identical. Code looks good, but this could help reduce maintenance burden.

Thanks!

Comment (madmikeross) [reply apps/rust-sdk/src/document.rs]: Great suggestion. Fixed here [9f90212](https://github.com/firecrawl/firecrawl/pull/2948/commits/9f90212210e7ae99d8ae38c10e88f10cf7401b9e)

**Comment by abimaelmartell** [comment]
Looks good, thank you so much for this contribution, will merge this in a moment.

Best,
Abimael Martell
